#! /usr/bin/env perl

use strict;
use warnings FATAL => 'all';
use Carp::Always;

# ------------------------------------------------------------------------

use File::Basename;
use Getopt::Std;

our $opt_h;

sub usage {
  my $progname = basename($0);
  print STDERR "Usage: $progname [options] (file.fna ...|<file.fna)\n";
  print STDERR "-h - print help\n";
  exit(@_);
}

my $stat = getopts('h');
if (!$stat) {
  usage(1);
}
if ($opt_h) {
  usage();
}

# ------------------------------------------------------------------------

my $meta;
my $seq = "";

sub emit {
  if (!defined($meta)) { return; }
  ( $meta !~ /\t/ ) || die "tab in meta,";
  ( $seq !~ /\t/ ) || die "tab in sequence,";
  print join("\t",$meta,$seq),"\n";
  $meta = undef;
  $seq = "";
}

while (<>) {
  chomp;
  if ( /^>/ ) {
    emit();
    $meta = $_;
  } else {
    $seq .= $_;
  }
}

emit();

